version: '3.8'

services:
  backend:
    build: ./backend
    image: kaxun/campus-guard-backend:latest  # Specify image name
    container_name: backend_container
    ports:
      - "8800:8800"
    environment:
      MONGO_URL: mongodb+srv://alabiabdullah1:Olasubomi123!@incident-reporting.45eivkr.mongodb.net/incident-reporting?retryWrites=true&w=majority&appName=incident-reporting

  frontend:
    build: ./frontend
    image: kaxun/campus-guard-frontend:latest  # Specify image name
    container_name: frontend_container
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  admin:
    build: ./admin
    image: kaxun/warmhands-admin:latest  # Specify image name
    container_name: admin_container
    ports:
      - "5174:5174"
    stdin_open: true
    tty: true
    depends_on:
      - backend
